-- CREATE DATABASE IF NOT EXISTS proteomics;


CREATE TABLE IF NOT EXISTS PHATR (
	seq_id TEXT NOT NULL,
	protein_name TEXT NOT NULL,
	sequence TEXT NOT NULL
	-- no_seq_chars INTEGER
);

-- LOAD DATA LOCAL INFILE './PHATRdb.txt' INTO TABLE PHATR
-- FIELDS TERMINATED BY '|'
-- LINES TERMINATED BY '\n';

CREATE TABLE IF NOT EXISTS THAOC (
	seq_id TEXT NOT NULL,
	protein_name TEXT NOT NULL,
	sequence TEXT NOT NULL
	-- no_seq_chars INTEGER
);

-- LOAD DATA LOCAL INFILE './THAOCdb.txt' INTO TABLE THAOC
-- FIELDS TERMINATED BY '|'
-- LINES TERMINATED BY '\n';

CREATE TABLE IF NOT EXISTS THAPS (
	seq_id TEXT NOT NULL,
	protein_name TEXT NOT NULL,
	sequence TEXT NOT NULL
	-- no_seq_chars INTEGER
);

LOAD DATA LOCAL INFILE './THAPSdb.txt' INTO TABLE THAPS
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';