-- CREATE DATABASE IF NOT EXISTS proteomics;


CREATE TABLE IF NOT EXISTS RBH (
	seq_id varchar(50) NOT NULL PRIMARY KEY,
	xy TEXT NOT NULL,
	xz TEXT NOT NULL
	-- no_seq_chars INTEGER
);


LOAD DATA LOCAL INFILE './THAPS.txt' INTO TABLE RBH
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';